name: Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: pnpm run build

      - name: Zip release
        run: zip -r obsidian-azure-blob-sync-plugin.zip ./dist/main.js ./manifest.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main.js
            manifest.json
            obsidian-azure-blob-sync-plugin.zip
