name: Build

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0

      - uses: pnpm/action-setup@v2
        with:
          version: 8.5.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Save artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution-files
          retention-days: 1
          path: |
            dist/main.js
            manifest.json

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: distribution-files

      - name: Zip files
        run: zip -r obsidian-azure-blob-sync-plugin.v${{ github.ref_name }}.zip ./dist/main.js ./manifest.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/main.js
            manifest.json
            obsidian-azure-blob-sync-plugin.v${{ github.ref_name }}.zip
